# Generated by Django 5.0.2 on 2024-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectura', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
